services:
  pixoo-downloader-info:
    build: .
    image: pixoo-downloader-info:latest
    container_name: pixoo-downloader-info
    network_mode: host
    restart: always
    environment:
      - BASE_URL=${BASE_URL}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL:-3}
      - PIXOO_IP=${PIXOO_IP:-}
